---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dhcrelay
  name: dhcrelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcrelay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dhcrelay
    spec:
      containers:
        - args:
            - -id
            - $(DHCP_DOWNSTREAM_INTERFACE)
            - -iu
            - $(DHCP_UPSTREAM_INTERFACE)
            - boots
          env:
            - name: DHCP_DOWNSTREAM_INTERFACE
              valueFrom:
                secretKeyRef:
                  name: tinkerbell
                  key: TINKERBELL_NETWORK_INTERFACE
            - name: DHCP_UPSTREAM_INTERFACE
              value: cni0
          image: docker.io/modem7/dhcprelay:latest
          imagePullPolicy: Always
          name: dhcrelay
          ports:
            - containerPort: 67
              hostPort: 67
              name: dhcp
              protocol: UDP
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhcrelay
  name: dhcrelay
spec:
  ports:
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: dhcp
  selector:
    app: dhcrelay
